import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const Torus = localFont({
  src: [
    {
        path: 'fonts/TorusRegular.otf',
        weight: '400',
        style: 'normal',
    },
    {
        path: 'fonts/TorusBold.otf',
        weight: '500',
        style: 'normal',
    },
    {
        path: 'fonts/TorusHeavy.otf',
        weight: '700',
        style: 'normal',
    },
    {
        path: 'fonts/TorusLight.otf',
        weight: '300',
        style: 'normal',
    },
    {
        path: 'fonts/TorusThin.otf',
        weight: '200',
        style: 'normal',
    },
    {
        path: 'fonts/TorusBold.otf',
        weight: '600',
        style: 'normal',
    },
    {
        path: 'fonts/TorusSemiBold.otf',
        weight: '600',
        style: 'normal',
    },
  ],
  variable: "--font-torus",
});

const Baloo = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Baloo.variable} ${Torus.variable} antialiased`}
        >
        {children}
      </body>
    </html>
  );
}
